# Match these literal values in the respective claims
issuer: https://token.actions.githubusercontent.com
# subject: repo:homburg/hello-actions:ref:refs/heads/main
# subject: repo:homburg/hello-actions
subject_pattern: "repo:homburg/hello-actions:.*"

permissions:
  contents: read
  issues: write
